# This file was auto-generated with gen_filelists.sh

set(Core_HDR_FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorFirstOfType.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledBoxInstancer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementStyle.h
	${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementStyleCache.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ContextInstancerDefault.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/PropertyParserKeyword.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementDefinition.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorOnlyChild.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorNoneInstancer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledHorizontal.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledImageInstancer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/PluginRegistry.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorEmpty.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetParser.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/XMLNodeHandlerTemplate.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/PropertyShorthandDefinition.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorNthOfType.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementTextDefault.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelector.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontEffectShadowInstancer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorLastOfType.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/TextureLayoutRow.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementBackground.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/PropertyParserString.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/TextureResource.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNode.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Clock.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledInstancer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledImage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledVerticalInstancer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorLastChild.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementHandle.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/EventDispatcher.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Pool.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/TemplateCache.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Template.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/UnicodeRange.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/EventIterators.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/XMLNodeHandlerBody.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/LayoutBlockBox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/WidgetSlider.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/LayoutInlineBoxText.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontFaceLayer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementImage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontFamily.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiled.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/PropertyParserColour.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/XMLParseTools.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/WidgetSliderScroll.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/LayoutBlockBoxSpace.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DocumentHeader.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/precompiled.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontFaceHandle.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorNthLastChild.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorFirstChild.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/LayoutLineBox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DebugFont.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontEffectNone.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontEffectShadow.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/TextureDatabase.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/PropertyParserNumber.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledVertical.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorNthChild.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/TextureLayoutRectangle.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/LayoutInlineBox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/GeometryDatabase.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontEffectOutlineInstancer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/TextureLayoutTexture.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontFace.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/TextureLayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/EventInstancerDefault.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementBorder.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/XMLNodeHandlerHead.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementDecoration.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StreamFile.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/LayoutEngine.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontEffectOutline.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetFactory.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorNthLastOfType.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FileInterfaceDefault.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/XMLNodeHandlerDefault.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorNone.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledHorizontalInstancer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StringCache.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontEffectNoneInstancer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledBox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorOnlyOfType.h
)

set(Core_PUB_HDR_FILES
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/FontEffect.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/TypeConverter.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/ElementScroll.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/SystemInterface.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Colour.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Box.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/ConvolutionFilter.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/EventListenerInstancer.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/ElementInstancerGeneric.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/FileInterface.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/MathTypes.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/ElementInstancer.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/PropertySpecification.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Property.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Plugin.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/ElementReference.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/StreamMemory.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/WString.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/EventListener.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/PropertyDefinition.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Decorator.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Texture.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/PropertyDictionary.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/StyleSheet.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/FontGlyph.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/ReferenceCountable.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/StringUtilities.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Vertex.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/ElementUtilities.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Factory.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Stream.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/GeometryUtilities.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Vector2.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/StyleSheetSpecification.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/RenderInterface.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/StyleSheetKeywords.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Core.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/FontDatabase.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Header.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Dictionary.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Types.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/XMLParser.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/ElementDocument.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/BaseXMLParser.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Debug.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/URL.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Input.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Event.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Geometry.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Font.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/ElementText.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/String.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Element.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/ScriptInterface.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/StringBase.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/EventInstancer.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/DecoratorInstancer.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Context.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/FontEffectInstancer.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Variant.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Math.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Log.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/Platform.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/XMLNodeHandler.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/PropertyParser.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core/ContextInstancer.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Core.h
)

set(Core_SRC_FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StreamMemory.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledVertical.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/EventInstancerDefault.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementHandle.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/XMLNodeHandlerBody.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/TextureDatabase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetParser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Core.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Template.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/XMLNodeHandler.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/String.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ReferenceCountable.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorLastOfType.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementBackground.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledHorizontal.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/EventDispatcher.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/EventListenerInstancer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StringCache.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementUtilities.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/TemplateCache.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledBoxInstancer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Event.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Clock.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/GeometryDatabase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorOnlyChild.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontEffectInstancer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementDecoration.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontEffect.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FileInterfaceDefault.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/XMLNodeHandlerTemplate.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ConvolutionFilter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiled.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/XMLNodeHandlerHead.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DocumentHeader.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ContextInstancer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledInstancer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Decorator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/BaseXMLParser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Box.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/PropertyDefinition.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Math.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementText.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/precompiled.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetSpecification.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontEffectNone.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/PluginRegistry.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementInstancer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/RenderInterface.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ContextInstancerDefault.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/LayoutInlineBoxText.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/TextureLayout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/PropertyDictionary.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorInstancer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Context.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/LayoutEngine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/WidgetSlider.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Property.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementStyle.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementStyleCache.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorNoneInstancer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Element.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontEffectOutlineInstancer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontDatabase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Texture.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementScroll.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontFaceLayer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/UnicodeRange.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FileInterface.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorNthLastChild.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontEffectShadow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetFactory.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorLastChild.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/LayoutBlockBoxSpace.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontEffectNoneInstancer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontFace.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Vector2.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/PropertyParserKeyword.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNode.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementDocument.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorEmpty.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledImageInstancer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontEffectOutline.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontFamily.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/WString.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/URL.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontEffectShadowInstancer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledHorizontalInstancer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorNone.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StreamFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Dictionary.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledImage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/EventInstancer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/TextureLayoutRow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/PropertySpecification.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/FontFaceHandle.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/SystemInterface.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementBorder.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Plugin.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/LayoutLineBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/TextureLayoutRectangle.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/TextureResource.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/LayoutBlockBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorNthOfType.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementImage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelector.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/GeometryUtilities.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorNthLastOfType.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/WidgetSliderScroll.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/XMLParseTools.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorFirstOfType.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementTextDefault.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/PropertyParserNumber.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/XMLNodeHandlerDefault.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/TextureLayoutTexture.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Stream.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/XMLParser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheet.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorFirstChild.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StringUtilities.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Log.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Variant.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorNthChild.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Geometry.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/DecoratorTiledVerticalInstancer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementReference.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/StyleSheetNodeSelectorOnlyOfType.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/PropertyParserString.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/PropertyParserColour.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Factory.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/ElementDefinition.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/LayoutInlineBox.cpp
)

set(Controls_HDR_FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/WidgetDropDown.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/InputTypeRange.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/WidgetSliderInput.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/WidgetTextInputSingleLine.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/WidgetTextInput.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/InputTypeButton.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/WidgetSlider.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/WidgetTextInputMultiLine.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/XMLNodeHandlerTabSet.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/InputTypeCheckbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/InputTypeSubmit.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/InputTypeRadio.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/ElementTextSelection.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/InputType.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/XMLNodeHandlerDataGrid.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/XMLNodeHandlerTextArea.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/WidgetTextInputSingleLinePassword.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/InputTypeText.h
)

set(Controls_PUB_HDR_FILES
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/DataQuery.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/ElementFormControlDataSelect.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/ElementFormControlTextArea.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/ElementTabSet.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/Controls.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/ElementFormControlSelect.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/SelectOption.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/ElementFormControlInput.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/ElementFormControl.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/Header.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/DataSource.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/ElementDataGrid.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/ElementDataGridExpandButton.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/ElementDataGridRow.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/Clipboard.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/DataFormatter.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/DataSourceListener.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/ElementForm.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls/ElementDataGridCell.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Controls.h
)

set(Controls_SRC_FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/SelectOption.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/WidgetTextInputSingleLinePassword.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/XMLNodeHandlerDataGrid.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/XMLNodeHandlerTextArea.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/WidgetDropDown.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/ElementTabSet.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/ElementFormControlTextArea.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/Clipboard.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/WidgetTextInputMultiLine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/DataSourceListener.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/WidgetSliderInput.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/ElementFormControlDataSelect.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/InputTypeSubmit.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/WidgetTextInput.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/Controls.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/InputTypeRadio.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/ElementDataGridRow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/ElementFormControlSelect.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/WidgetSlider.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/ElementDataGridExpandButton.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/InputTypeText.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/InputTypeCheckbox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/InputType.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/ElementFormControlInput.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/ElementDataGrid.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/ElementTextSelection.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/XMLNodeHandlerTabSet.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/DataQuery.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/ElementForm.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/InputTypeButton.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/InputTypeRange.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/ElementDataGridCell.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/ElementFormControl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/WidgetTextInputSingleLine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/DataFormatter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Controls/DataSource.cpp
)

set(Debugger_HDR_FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/ElementLog.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/SystemInterface.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/InfoSource.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/Plugin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/LogSource.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/ElementInfo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/BeaconSource.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/Geometry.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/MenuSource.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/ElementContextHook.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/CommonSource.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/FontSource.h
)

set(Debugger_PUB_HDR_FILES
    ${PROJECT_SOURCE_DIR}/include/Rocket/Debugger/Header.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Debugger/Debugger.h
    ${PROJECT_SOURCE_DIR}/include/Rocket/Debugger.h
)

set(Debugger_SRC_FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/ElementInfo.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/Debugger.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/ElementLog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/ElementContextHook.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/SystemInterface.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/Plugin.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Debugger/Geometry.cpp
)
